{{- if index .Values "data-prepper" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: observability-stack-dp-pipeline
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  pipelines.yaml: |
    otlp-pipeline:
      delay: 10
      source:
        otlp:
          port: 21890
          ssl: false
      route:
        - logs: 'getEventType() == "LOG"'
        - traces: 'getEventType() == "TRACE"'
      sink:
        - pipeline:
            name: "otel-logs-pipeline"
            routes: ["logs"]
        - pipeline:
            name: "otel-traces-pipeline"
            routes: ["traces"]

    otel-logs-pipeline:
      workers: 5
      delay: 10
      source:
        pipeline:
          name: "otlp-pipeline"
      buffer:
        bounded_blocking: {}
      processor:
        - copy_values:
            entries:
              - from_key: "time"
                to_key: "@timestamp"
      sink:
        - opensearch:
            hosts: ["https://opensearch-cluster-master:9200"]
            username: {{ .Values.opensearchUsername | default "admin" | quote }}
            password: {{ .Values.opensearchPassword | quote }}
            insecure: true
            index_type: log-analytics-plain

    otel-traces-pipeline:
      delay: 100
      source:
        pipeline:
          name: "otlp-pipeline"
      sink:
        - pipeline:
            name: "traces-raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"

    traces-raw-pipeline:
      source:
        pipeline:
          name: "otel-traces-pipeline"
      processor:
        - otel_traces: {}
      sink:
        - opensearch:
            hosts: ["https://opensearch-cluster-master:9200"]
            username: {{ .Values.opensearchUsername | default "admin" | quote }}
            password: {{ .Values.opensearchPassword | quote }}
            insecure: true
            index_type: trace-analytics-plain-raw

    service-map-pipeline:
      delay: 100
      source:
        pipeline:
          name: "otel-traces-pipeline"
      processor:
        - otel_apm_service_map:
            group_by_attributes: [telemetry.sdk.language]
            window_duration: 10s
      route:
        - otel_apm_service_map_route: 'getEventType() == "SERVICE_MAP"'
        - service_processed_metrics: 'getEventType() == "METRIC"'
      sink:
        - opensearch:
            hosts: ["https://opensearch-cluster-master:9200"]
            username: {{ .Values.opensearchUsername | default "admin" | quote }}
            password: {{ .Values.opensearchPassword | quote }}
            index_type: otel-v2-apm-service-map
            routes: [otel_apm_service_map_route]
            insecure: true
        - prometheus:
            url: "http://{{ .Release.Name }}-prometheus-server:80/api/v1/write"
            threshold:
              max_events: 500
              flush_interval: 5s
            routes: [service_processed_metrics]
{{- end }}
